<% Option Explicit %>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<html>
<head>
	<title>YCode Script</title>
</head>

<body>
<%
'This program uses regular expressions to find and replace yCode with HTML. It works in three steps:
'1)	A user defines a YCode. Codes have four properties: 
'	1.1)	A StartTag. All tags are in the [tagname] format.
'	1.2)	Optional EndTag. End tags are in the [/tagname] format.
'	1.3)	Optional Argument(s). Arguments appear after the "=" sign in the tag, they appear in the
'			[url=argument1; argument2; argument3;]. An unlimited number of arguments may be used. There
'			are limitations, however, in the sense that the arguments are "dumb", they cannot perform 
'			calculations and there is no way to validate user input.
'	1.4)	HTML template to replace the tag. This is used in step 3.
'
'2) A regex pattern is generated from the information gathered. Patterns are generated in two steps:
'	2.1)	If the code uses any arguments, a pattern is generated to match the arguments in the code.
'			The arguments pattern is constructed with "=(?:\s{0,})", followed by
'			the "([^\];]+)(?:;\s{1,}|;)" pattern x number of times, where x is the number of arguments
'			used for the particular code. If there are no arguments being used, this step is ommitted.
'	2.2)	Now a pattern for matching the code is generated, which matches the general form
'			[{tagname}{=optional arguments}]{text}[/{tagname}] or the form [{tagname}{=optional arguments}]
'			dependong on whether an endtag is used or not. This pattern is generated by joining the
'			arguments pattern from above like this:
'				"\[{tagname}" & BuildArguments & "\](.*?)\[\/{tagname}\]"
'	Here is an example pattern generated for the tag [url=argument1]text[/url]:
'				\[url=(?:\s{0,})([^\];]+)\](.*?)\[\/url\]
'
'3)	After constructing the pattern, a simple regex search/replace is performed. This is performed in 2
'	steps:
'	3.1)	The user must define HTML to replace the YCode once it has been found. The special code
'			"$arg{N}", where {N} is an integer from 1 to any number of arguments, is used to access the
'			arguments in a YCode. The special code "$text" is used to access text found between
'			two tags. Example template for hyperlinks:
'				<a href="$arg1">$text</a>
'	3.2)	The above is actually a friendly format for the reader, but the regex engine can't actually
'			use that form, so it replaces all of the "$arg{N}" with "${N}", and "$text" with "${N+1}".
'			This is a kind of a source code that is used so the regex engine knows where to make all the
'			right replacements. So in actuality, the code defined by the user above will become:
'				<a href="$1">$2</a>
'			This works because the regex engine captures all of the arguments and text between tags, but
'			it assigns all the captures numerically (which is hard for the user to read). Fortunately, 
'			due to the way that tags are constructed, all the arguments are captured first, and the 
'			text between tags is captured last. So the first argument is assigned to $1, the second argument
'			is assigned to $2, and so on; the text between tags is actually an argument itself, and it gets
'			assigned to ${number of arguments + 1}.
'			
'			When defning HTML, you can use the same argument as many times as you like, for instance a 
'			interesting you may choose to format HTML like this...
'				<i>$text</i> [<a href="$arg1">$arg1</a>]
'			...which  will seperate the URL and description text of the link, so that the URL is displayed
'			as a link in brackets to the side of the description text.
'
'Here's an example of how everything works all at once:
'1)	User defines this tag:
'		url, endtag=true, accepts 1 argument
'	User defines this HTML as the template of the new tag:
'		<a href="$arg1">$text</a>
'
'2)	The code generates a pattern to match the text.
'
'3) The code finds and replaces all the YCode with the HTML template. So that:
'		[url=http://www.fstdt.com]Fundies![/url]
'	becomes:
'		<a href="http://www.fstdt.com">Fundies!</a>.


	Function FormatText(myText)
		'Disabling HTML
		myText = Server.HTMLEncode(myText)
	
		Dim regEx
		Set regEx = New RegExp
		
			regex.global = true
			regex.IgnoreCase = true
			
			regex.Pattern = BuildPattern("b", True, 0)
			myText = regex.replace(myText, FixReplace("<b>$text</b>", 0))
			
			regex.Pattern = BuildPattern("u", True, 0)
			myText = regex.replace(myText, FixReplace("<u>$text</u>", 0))
			
			regex.Pattern = BuildPattern("i", True, 0)
			myText = regex.replace(myText, FixReplace("<i>$text</i>", 0))
			
			regex.Pattern = BuildPattern("url", True, 1)
			myText = regex.replace(myText, FixReplace("<a href=""$arg1"">$text</a>", 1))
			
			regex.Pattern = BuildPattern("color", True, 1)
			myText = regex.replace(myText, FixReplace("<font color=""$arg1"">$text</font>", 1))
			
			regex.Pattern = BuildPattern("fstdt", True, 1)
			myText = regex.replace(myText, FixReplace("<a href=""http://www.fstdt.com/comments.asp?id=$arg1"">$text</a>", 1))
			
			regex.Pattern = BuildPattern("randomquote", false, 3)
			myText = regex.replace(myText, FixReplace("<img src=""http://www.fstdt.com/signature/sig.asp?width=$arg1&color=$arg2&size=$arg3"">", 1))
			
			regex.Pattern = BuildPattern("articolo", false, 1)
			myText = regex.replace(myText, FixReplace(" <a href=""product.asp?idpro=$arg1"">articolo</a> ", 1))


			
			'Note: repeating the "regex.pattern" and "myText = regex.replace" lines of code over and over
			'is very tedious. I've only done it this way for simplicity, but in reality a table could hold
			'this information like this:
			'
			'	Table: YCodes
			'		ID		Code		EndTag		Arguments		ReplacementHTML
			'		1		b			true		0				<b>$text</b>
			'		2		url			true		1				<a href="$arg1">$text</a>
			'		3		fstdtquote	false		3				<img src="http://www.fstdt.com/signature/sig.asp?width=$arg1; color=$arg2; size=$arg3">
			'		etc.
			'
			'By looping through the table, you accomplish all of the information below in 5 or 6 lines of
			'code. I've actually had sites that used hundreds of YCodes stored in a table very successfully.
			'
			'One thing to notice about this code is the fact that if you use the wrong number of arguments
			'for a code, it won't format at all. A way to get around this is to add an extra column called
			'DefaultHTML, and then call the BuildPattern function again only this time you tell it that
			'there are no arguments like this: BuildPattern(someCode, true, 0). Visual demonstration:
			'
			'		ID		Code		EndTag		Arguments		ReplacementHTML				DefaultHTML
			'		2		url			true		1				<a href="$arg1">$text</a>	<a href="$text">$text</a>
			'
			'		You'd use this ASP code:
			'			someCode = "url"
			'			regex.Pattern = BuildPattern(someCode, True, 1)
			'			myText = regex.replace(myText, FixReplace(ReplacementHTML, 1))
			'			regex.Pattern = BuildPattern(someCode, True, 0)		rem Default value if no arguments are specified
			'			myText = regex.replace(myText, FixReplace(DefaultHTML, 0))
			'
			'		Such that:
			'			[url=http://www.fstdt.com]Fundies![/url]
			'		formats as:
			'			<a href="http://www.fstdt.com">Fundies!</a>
			'	
			'		And the same code with no parameters:
			'			[url]http://www.fstdt.com[/url]
			'		formats as:
			'			<a href="http://www.fstdt.com">http://www.fstdt.com</a>
			
			
			'Adding line breaks
			MyText = Replace(MyText, vbNewline, "<br />", 1, -1, vbBinaryCompare)
			
			FormatText = myText
		Set regEx = Nothing
	End Function
	
	Function BuildPattern(myCode, UseEndTag, numArguments)
	Dim I, myTemp
	Dim BuildArguments
		If numArguments Then
			BuildArguments = "=(?:\s{0,})"
			
			For I = 1 to numArguments
				BuildArguments = BuildArguments & "([^\];]+)(?:;\s{1,}|;)"
			Next
			
			'Stripping superfluous whitespace-catcher, we don't need this, otherwise it screws up the code.
			myTemp = "(?:;\s{1,}|;)"
			If Right(BuildArguments, len(myTemp)) = myTemp then
				BuildArguments = Left(BuildArguments, len(BuildArguments) - len(myTemp))
			end if
		End if
		
		If UseEndTag = True then
			BuildPattern = "\[" & myCode & BuildArguments & "\](.*?)\[\/" & myCode & "\]"
		else
			BuildPattern = "\[" & myCode & BuildArguments & "\]"
		end if
	End Function
	
	Function FixReplace(myCode, numArguments)
		if numArguments then
			myCode = replace(myCode, "$arg", "$", 1, -1, vbtextcompare)
			myCode = replace(myCode, "$text", "$" & numArguments + 1, 1, -1, vbtextcompare)
		else
			myCode = replace(myCode, "$text", "$1", 1, -1, vbtextcompare)
		end if
		
		FixReplace = myCode
	End Function
	 
	
Dim myQuote
myQuote = request("quote")
%>

<form action="ycode.asp" method="post">
<textarea name="quote" rows="10" cols="60"><%
if MyQuote <> "" then
	response.write MyQuote
else %>This was a short little snippet I wrote in response to the crappy [url=http://www.phpbb.com]PHPbb[/url] software. It allows you to define [i]your own[/i] custom bbCodes (I like to call them [b]YCodes[/b]).

This code could be useful for people who are developing messageboards, content management systems, blogs, etc. and would like to easily allow their users to format text.<%end if
%></textarea>
<div><input type="Submit"></div>
</form>

<p>
Available codes are:<br>
[b]<i>text</i>[/b]<br>
[i]<i>text</i>[/i]<br>
[u]<i>text</i>[/u]<br>
[url=<i>some_Link</i>]<i>text</i>[/url]<br>
[color=<i>font_color</i>]<i>text</i>[/color]<br>
[fstdt=<i>ID_of_fundie_post</i>]<i>text</i>[/b]<br>
[randomquote=<i>image_width</i>; <i>font_color</i>; <i>font_size</i>]<br>
</p>

<hr>

<p><%=FormatText(myQuote)%></p>

</body>
</html>
